# Site settings
title: x64dbg
tagline: Official x64dbg blog!
email: blog@x64dbg.com
description: Official x64dbg blog!
baseurl: /blog
#url: http://x64dbg.com
twitter_username: x64dbg
github_username: x64dbg

paginate: 5

github:
  repo: https://github.com/x64dbg/blog

author:
  name: 'x64dbg'
  url: http://x64dbg.com

# Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-gist, rouge]