# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: x64dbg blog
email: blog@x64dbg.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about x64dbg.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://x64dbg.com/blog" # the base hostname & protocol for your site
twitter_username: x64dbg
github_username: x64dbg

# Build settings
markdown: kramdown
