# Site settings
title: x64dbg
tagline: Official x64dbg blog!
description: Official x64dbg blog!
baseurl: /blog
url: http://x64dbg.com/blog
twitter_username: x64dbg
github_username: x64dbg

paginate: 3

github:
  repo: https://github.com/x64dbg/blog

author:
  name: 'x64dbg'
  url: http://x64dbg.com
  email: blog@x64dbg.com

# Build settings
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]