# Site settings
title: x64dbg blog
tagline: 'Blog about x64dbg...'
email: blog@x64dbg.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about x64dbg.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://x64dbg.com/blog" # the base hostname & protocol for your site
twitter_username: x64dbg
github_username: x64dbg

paginate: 5

github:
  repo: https://github.com/x64dbg/blog

author:
  name: 'x64dbg'
  url: http://x64dbg.com

# Build settings
markdown: kramdown
highlighter: rogue
gems: [jekyll-paginate, jekyll-gist, rouge]